pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        maven {
            credentials {
                username 'oCTwYT'
                password 'D0QXlbW7Pb'
            }
            url 'https://packages.aliyun.com/maven/repository/2366325-release-BS0F4j/'
        }
        maven {
            url "https://jfrog.anythinktech.com/artifactory/overseas_sdk"
        }
        maven {
            url "https://android-sdk.is.com/"
        }

        //pangle
        maven {
            url 'https://artifact.bytedance.com/repository/pangle'
        }

        //openmediation
        maven { url 'https://dl.openmediation.com/omcenter/' }

        //mintegral
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
        }

        //Anythink(Core)
        maven {
            url "https://anythink.jfrog.io/artifactory/android_sdk"
        }

        //Vungle
        maven {
            url "https://s01.oss.sonatype.org/content/groups/staging/"
        }

        //Chartboost
        maven {
            url "https://cboost.jfrog.io/artifactory/helium"
        }

        //Tapjoy
        maven {
            url "https://sdk.tapjoy.com/"
        }

        maven { url 'https://developer.huawei.com/repo/' }


        maven { url 'https://maven.singular.net/' }

        //Chartboost 三星要加
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-ads"
        }
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-mediation"
        }

        maven {
            url "https://verve.jfrog.io/artifactory/verve-gradle-release"
        }
        maven { url "https://artifactory.bidmachine.io/bidmachine" }

        maven {
            url "https://bitbucket.org/sdkcenter/sdkcenter/raw/release"
        }
    }
}

rootProject.name = "MobileClean250729"
include ':app'
